import classNames from 'classnames';
import Head from 'next/head';
import Link from 'next/link';

import { menuItems } from '.';

const Contact = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative p-20">
        <div className="flex justify-between gap-20">
          <h1 className="text-6xl mb-20">MAX MONTGOMERY</h1>
          <div className="flex grow justify-evenly">
            {menuItems.map((item, i) => (
              <Link href={item.href} key={item.href}>
                <a
                  className={classNames("anton text-xl", {
                    "text-selected disableClick": i === 2,
                  })}
                >
                  {item.name}
                </a>
              </Link>
            ))}
          </div>
        </div>
        <a href="mailto:maxmontyphoto@gmail.com">
          Contact me:
          <br />
          Email: maxmontyphoto@gmail.com
        </a>
      </div>
    </>
  );
};

export default Contact;
